### PR TITLE
fix: invalid File instance check

### PR DESCRIPTION
**Pull request by triniwiz**

### CODE REVIEW

**Comment by jerbob92** [comment]
Can you tell me why this is needed?

**Comment by triniwiz** [comment]
By importing `File` you will be checking for the wrong instance since I believe you meant to check for the File available on [global](https://github.com/NativeScript/NativeScript/blob/master/packages/core/xhr/index.ts#L462) vs the [import](https://github.com/klippa-app/nativescript-http/blob/master/src/http.ios.ts#L1) , another thing you seem to be ignoring the `value.name` even it it was set which seems to cause issue with trying to upload to an [s3 compatible api ](https://github.com/triniwiz/nativescript-plugins/blob/master/packages/nativescript-supabase-storage/lib/StorageFileApi.ts)

**Comment by jerbob92** [comment]
A Blob doesn't have a filename, that's why there is this code:

```
let filename = "";
if (value instanceof File) {
	filename = value.name;
}
```

But you might be correct that that it's using the wrong instance check, however, it should only need 1 of the 2 changes to fix it.

**Comment by triniwiz** [comment]
Right missed the extra check if the blob there is a file however value.name should return undefined when it's not a file an will fallback to the empty string 🤷🏽‍♂️

**Comment by jerbob92** [comment]
> Right missed the extra check if the blob there is a file however value.name should return undefined when it's not a file an will fallback to the empty string 🤷🏽‍♂️

That's what I'm saying, if we use the `value.name || ""` fix, then we don't need the global File import fix, en when we use the File import fix we don't need the `value.name || ""`

**Comment by triniwiz** [comment]
true but I was just working with what was given 😄

**Pull request merged**
